// Generated by Copilot
import {
  PrismaClientKnownRequestError,
  type InputJsonValue,
} from "@prisma/client/runtime/library";
import type { WebhookEvent } from "@clerk/backend/webhooks";

import prisma from "@senara/db";

type UserMutationEvent = Extract<
  WebhookEvent,
  { type: "user.created" | "user.updated" }
>;
type UserMutationData = UserMutationEvent["data"];
type UserDeletedData = Extract<WebhookEvent, { type: "user.deleted" }>["data"];

function get_clerk_id(event: WebhookEvent): string | null {
  switch (event.type) {
    case "user.created":
    case "user.updated":
      return event.data.id;
    case "user.deleted":
      return event.data.id ?? null;
    case "organization.created":
    case "organization.updated":
      return event.data.id;
    case "organization.deleted":
      return event.data.id ?? null;
    case "organizationMembership.created":
    case "organizationMembership.updated":
    case "organizationMembership.deleted":
      return event.data.organization.id;
    default:
      return null;
  }
}

function get_primary_email(user: UserMutationData): string | null {
  return user.email_addresses[0]?.email_address ?? null;
}

async function upsert_user_profile(user: UserMutationData): Promise<void> {
  const now = new Date();
  const clerk_user_id = user.id;

  if (!clerk_user_id) {
    throw new Error("Missing Clerk user id in user webhook payload");
  }

  await prisma.user_profile.upsert({
    where: {
      clerk_user_id,
    },
    create: {
      clerk_user_id,
      email: get_primary_email(user),
      first_name: user.first_name,
      last_name: user.last_name,
      username: user.username,
      image_url: user.image_url,
      last_event_at: now,
      deleted_at: null,
    },
    update: {
      email: get_primary_email(user),
      first_name: user.first_name,
      last_name: user.last_name,
      username: user.username,
      image_url: user.image_url,
      last_event_at: now,
      deleted_at: null,
    },
  });
}

async function mark_user_deleted(user: UserDeletedData): Promise<void> {
  const now = new Date();
  const clerk_user_id = user.id;

  if (!clerk_user_id) {
    throw new Error("Missing Clerk user id in user.deleted webhook payload");
  }

  await prisma.user_profile.upsert({
    where: {
      clerk_user_id,
    },
    create: {
      clerk_user_id,
      last_event_at: now,
      deleted_at: now,
    },
    update: {
      last_event_at: now,
      deleted_at: now,
    },
  });
}

async function handle_webhook_event(event: WebhookEvent): Promise<void> {
  switch (event.type) {
    case "user.created":
    case "user.updated":
      await upsert_user_profile(event.data);
      return;
    case "user.deleted":
      await mark_user_deleted(event.data);
      return;
    case "organizationMembership.created":
    case "organizationMembership.updated":
    case "organizationMembership.deleted":
      return;
    default:
      return;
  }
}

export async function process_clerk_webhook_event(
  event: WebhookEvent,
  svix_id: string,
): Promise<void> {
  const clerk_id = get_clerk_id(event);

  try {
    await prisma.clerk_webhook_event.create({
      data: {
        svix_id,
        event_type: event.type,
        clerk_id,
        payload: event as unknown as InputJsonValue,
      },
    });
  } catch (error) {
    if (
      error instanceof PrismaClientKnownRequestError &&
      error.code === "P2002"
    ) {
      return;
    }

    throw error;
  }

  try {
    await handle_webhook_event(event);

    await prisma.clerk_webhook_event.update({
      where: {
        svix_id,
      },
      data: {
        clerk_id,
        processed_at: new Date(),
      },
    });
  } catch (error) {
    await prisma.clerk_webhook_event
      .delete({
        where: {
          svix_id,
        },
      })
      .catch(() => undefined);

    throw error;
  }
}
