// Generated by Copilot
import { process_clerk_webhook_event } from "@senara/api";
import { verifyWebhook } from "@clerk/nextjs/webhooks";
import type { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const svixId = req.headers.get("svix-id");

  if (!svixId) {
    return new Response("Missing svix-id header", { status: 400 });
  }

  let event;

  try {
    event = await verifyWebhook(req);
  } catch (error) {
    console.error("Webhook verification failed:", error);
    return new Response("Verification failed", { status: 400 });
  }

  try {
    await process_clerk_webhook_event(event, svixId);
  } catch (error) {
    console.error("Webhook processing failed:", error);
    return new Response("Processing failed", { status: 500 });
  }

  return new Response("OK", { status: 200 });
}
